version: "3"

services:
  mongo:
    image: mongo:4.0
    volumes:
      - ./brand-report-backend/docker/mongo/db/:/data/db/
    restart: always
    ports:
      - 27019:27017
  brand-report-backend:
    build: ./brand-report-backend/docker/backend/
    ports:
      - 8086:8080
    restart: always
    environment:
      BRAND_FILE: /data/brand.json
      INDEX_FILE: /data/index.json
      COLLECTION_FILE: /data/collection.json
    volumes:
      - ./brand-report-backend/docker/backend/logs:/var/lib/message/brand-report-backend
      - ./brand-report-backend/docker/backend/data:/data
    depends_on:
      - mongo
  brand-user-authorization-backend:
    build: ./brand-user-authorization-backend/docker/backend/
    ports:
      - 8085:8081
    restart: always
    volumes:
      - ./brand-user-authorization-backend/docker/backend/data:/data
    depends_on:
      - brand-report-backend
  brand_questionniare:
    build: ./BrandAnalysis-Questionnaire/docker
    ports:
      - 8087:8000
    volumes:
      - ./BrandAnalysis-Questionnaire:/BrandAnalysis-Questionnaire   #挂载login-register/ 目录下的所有文件到容器的/login-register/目录中
    command: bash ./docker/docker-start.sh  # 执行命令，有多种格式
    restart: always
    depends_on:
      - brand-user-authorization-backend
